### POST request to get the jwt token

POST http://localhost:4005/api/v1/auth/login
Content-Type: application/json

{
    "email": "testuser@test.com",
    "password": "password@123"
}

{% client.global.set("token", response.body.token) %}

###